# Generated by Django 5.2.4 on 2025-07-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("office_code", models.CharField(max_length=10)),
                (
                    "lob",
                    models.CharField(
                        choices=[
                            ("fire", "Fire"),
                            ("marine_cargo", "Marine Cargo"),
                            ("marine_hull", "Marine Hull"),
                            ("package", "Package"),
                            ("liability", "Liability"),
                            ("health", "Health"),
                            ("motor_od", "Motor OD"),
                            ("motor_tp", "Motor TP"),
                            ("personal_accident", "Personal Accident"),
                            ("aviation", "Aviation"),
                            ("engineering", "Engineering"),
                            ("others", "Others"),
                        ],
                        max_length=20,
                        verbose_name="LOB",
                    ),
                ),
                ("segment", models.CharField(max_length=10)),
                ("proposal_number", models.CharField(max_length=20)),
                (
                    "reason_for_escalation",
                    models.TextField(help_text="Copy and paste from GC"),
                ),
                (
                    "format_filled",
                    models.BooleanField(
                        max_length=10,
                        verbose_name="Whether format is filled and sent as prescribed",
                    ),
                ),
                (
                    "date_of_email_sent",
                    models.DateField(verbose_name="Date of email sent to RO"),
                ),
                ("oo_remarks", models.TextField(verbose_name="OO Remarks")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("clarification", "Clarification required from OO"),
                            ("pending_ho", "Sent to HO"),
                            ("approved_ho", "HO approved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="RO Action",
                    ),
                ),
                ("ro_remarks", models.TextField(verbose_name="RO remarks")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
