# Generated by Django 5.2.4 on 2025-07-14 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineOfBusiness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lob_name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="proposal",
            name="lob",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposal.lineofbusiness",
            ),
        ),
        migrations.CreateModel(
            name="ProductName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                (
                    "lob",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proposal.lineofbusiness",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="proposal",
            name="segment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposal.productname",
            ),
        ),
    ]
