# Generated by Django 5.2.4 on 2025-07-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proposal", "0002_lineofbusiness_alter_proposal_lob_productname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("format", models.FileField(upload_to="proposal_formats/")),
            ],
        ),
        migrations.AlterField(
            model_name="lineofbusiness",
            name="lob_name",
            field=models.CharField(max_length=20, verbose_name="LOB"),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="lob",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="proposal.lineofbusiness",
                verbose_name="LOB",
            ),
        ),
    ]
